spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeland
    username: quimba
    password: secretofthesand
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
